version: "3.3"
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
          - testdb:/var/lib/postgresql/data
          - ./create-table.sql:/docker-entrypoint-initdb.d/create-table.sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: testdb
      POSTGRES_HOST_AUTH_METHOD: trust

  employees:
    build:
       context: .

    expose:
          - 4000
    ports:
      - "4000:4000"
    environment:
       connectionString: postgres://postgres:1234@localhost:5432/testdb
       POSTGRES_HOST: host.docker.internal
       POSTGRES_USER: postgres
       POSTGRES_PASSWORD: postgres
       POSTGRES_DB: testdb

    depends_on:
      - postgres
volumes:
    testdb:
